# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.tammytang.com
title: Tammy
email: tammytongcn@gmail.com
author: Tammy Tang
description: "Tammy's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/tammysilva 
  - icon: envelope-o
    title: email
    url: mailto:tammytongcn@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/jiaxint/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/tttoms

